version: '3'
services:
  jekyll:
    build: .
    image: akirakoyasu/akirakoyasu.github.io
    working_dir: /srv/jekyll
    command:
      - bundle
      - exec
      - jekyll
      - serve
      - --host
      - 0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - $PWD:/srv/jekyll
